[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#0B1326"
secondaryBackgroundColor = "#171F33"
textColor = "#DAE2FD"
font = "sans serif"
